# docker-compose -f ./mysql-single.yml up -d

version: '3.9'
services:
  my_blog:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - SERVER_PORT=3000
    volumes:
      - ./:/app

  mysql_env_01:
    container_name: mysql_env_01
    image: mysql
    # restart: always
    restart: on-failure
    privileged: true
    hostname: 'mysql_env_01'
    network_mode: bridge
    # environment:
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      # - /mnt/remote/docker_compose/env/mysql.env
      - MYSQL_USER=sumu
      - MYSQL_PASSWORD=123456
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    #   --explicit_defaults_for_timestamp=true
    #   --lower_case_table_names=1
    #   --max_allowed_packet=128M;
    ports:
      - 3306:3306
      # - 9111:9104
    volumes:
      # - /etc/localtime:/etc/localtime
      - ./mnt/remote_data/mysql/mysql-env-05/conf:/etc/mysql/
      - ./mnt/remote_data/mysql/mysql-env-05/data:/var/lib/mysql
      - ./mnt/remote_data/mysql/mysql-env-05/mysql-files:/var/lib/mysql-files
      - ./mnt/remote_data/mysql/mysql-env-05/log:/var/log/mysql
      - ./mnt/remote_data/mysql/mysql-env-05/sock/:/var/run/mysqld
    # networks:
    #   - safety-net
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
  # mysql_exporter_01:
  #   container_name: mysql_exporter_01
  #   image: prom/mysqld-exporter
  #   restart: on-failure
  #   # privileged: true
  #   hostname: 'mysql_exporter_01'
  #   network_mode: bridge
  #   # network_mode: 'service:mysql_env_01'
  #   # network_mode: 'container:mysql_env_01'
  #   # environment:
  #   env_file:
  #     - /mnt/remote/docker_compose/env/mysql_exporter/mysql_01.env
  #   ports:
  #     - 9111:9104
  #   # volumes:
  #   depends_on:
  #     - mysql_env_01
